." Manpage for mapdircmp
.".RI [ underlined ]
.TH mapdircmp 1 "April 2020" "mapdircmp" "Manpage for mapdircmp"
.SH NAME
mapdircmp \- Compare directory trees with mapdir(1)
.SH SYNOPSIS
.BR "mapdircmp " "[-hkv] [-x excludes_file] savefile1 dirtree1 savefile2 dirtree2"
.SH DESCRIPTION
mapdircmp is a wrapper script around the \fBmapdir\fR(1) utility, that makes the verification of directory trees, that are assumed to be equal, easier to perform. The savefile arguments will be generated in the invoking user's home directory by default. The following options are understood:

.SH OPTIONS
.TP
.B -h
print usage information and exit.
.TP
.B -k
keep the savefiles.
.TP
.B -v
be more verbose.
.TP
.B -x excludes_file
read the files to be excluded from excludes_file. Entries are expected to contain the full path to file and are read line by line.
.SH EXAMPLE
.PP
Verify the consistency between /path/to/dir1 and /path/to/dir2 and keep the savefiles:
.PP
mapdircmp -k dir1.txt /path/to/dir1 dir2.txt /path/to/dir2
.br
.SH SEE ALSO
\fBmapdir\fR(1)
.SH BUGS
Please report when found.
.SH AUTHOR
Oliver Mahmoudi (contact@olivermahmoudi.com)
