#!/bin/sh

# Copyright (c) 2020 Oliver Mahmoudi
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions 
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

### mapdircmp - a comparison utility for mapdir

k_flag=0			# keep savefiles flag
v_flag=0			# verbose flag

usage()
{
	echo "usage: mapdircmp [-hkv] savefile1 dirtree1 savefile2 dirtree2"
	echo "	-h: print usage information and exit"
	echo "	-k: keep savefiles"
	echo "	-v: ve more verbose"
}

process_files()
{
	local _savefile _directory

	_savefile=$1
	_directory=$2
	
	if [ $v_flag -eq 1 ] ; then
		mapdir -fht -s $_savefile $_directory
	else
		mapdir -fht -s $_savefile $_directory > /dev/null 2>&1
			if [ $? -ne 0 ] ; then
				echo "Error while running: mapdir -fht -s $_savefile $_directoy"
				exit -1
			fi
	fi
}

# Point of entry

while getopts ":hkv" opt ; do
        case $opt in
                h)
                        usage
						exit 0
                        ;;
                k)
                        k_flag=1		# keep savefiles flag
                        ;;
                v)
                        v_flag=1		# be more verbose
                        ;;
                \?)
                        echo "unkown flag: -$OPTARG."
                        usage
                        exit 1
                        ;;
        esac
done

shift $((OPTIND-1))

if [ $# -ne 4 ] ; then
	usage
	exit -1
fi

# 1st run
process_files $1 $2

# 2nd run
process_files $3 $4

# Check 4 equality
diff ~/$1 ~/$3 > /dev/null 2>&1
if [ $? -eq 0 ] ; then
	echo "The files or directory trees are equal."
else
	echo "The files or directory trees differ."
fi

if [ $k_flag -eq 0 ] ; then
	rm ~/$1 ~/$3
fi

exit 0
