." Manpage for mapdir
.".RI [ underlined ]
.TH mapdir 1 "December 2018" "mapdir 1.2" "Manpage for mapdir"
.SH NAME
mapdir \- Map directory structures
.SH SYNOPSIS
.BR "mapdir " "[-dfhnpt] [-s savefile] [/path/to/file]"
.SH DESCRIPTION
The mapdir utility is used to map the structure of files and most notably folder hierarchies. Unless overridden with the -n or -s options, the results are stored in a report file in the invoking user's home directory, according to the following naming convention: mapdir_path_to_file_date.txt. If the file mapped is a regular file, then mapdir also reports its size in bytes and the file's md5 or sha256 checksum. If upon invocation no argument is passed to mapdir, then the utility maps the structure of the current working directory.

The utility mainly aims to facilitate verifying the consistency between two (or more) file hierarchies that contain the same files, as the generated report files can subsequently be passed to the \fBdiff(1)\fR utility. When using mapdir to this end, it should generally be invoked with the -f switch.

.SH OPTIONS
.TP
.B -d
only parse non-hidden files.
.TP
.B -f
omit reporting the name of the starting directory in the report file.
.TP
.B -h
use the sha256sum message digest instead of md5sum.
.TP
.B -n
only print to stdout, i.e. don't generate a savefile. This option overrides the -s option.
.TP
.B -p
print a tree view of the directory. This option requires the -f option to work.
.TP
.B -s savefile
save the report in savefile.
.TP
.B -t
generate a statistical report of the kinds of files mapped.
.SH EXAMPLES
.PP
1. Verify the consistency between /path/to/dir1 and /path/to/dir2:
.PP
mapdir -fh -s dir1_map.txt /path/to/dir1
.br
mapdir -fh -s dir2_map.txt /path/to/dir2
.br
diff ~/dir1_map.txt ~/dir2_map.txt
.PP
2. Map the structure of /path/to/dir in a tree like view to stdout:
.PP
mapdir -fnp /path/to/dir
.SH BUGS
Please report when found.
.SH AUTHOR
Oliver Mahmoudi (contact@olivermahmoudi.com)
